# Generated by Django 5.1.2 on 2024-10-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_content_construct_file_content_cypher'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name_os',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
